### PR TITLE
Removed auth check from add payment callback.

### PR DESCRIPTION
**Pull request by mikl**
The addPayment Alma method does not require authentication, so this
check is uneccessary, and might cause problems with expiring sessions,
or using a different session backend than the database.

We were having issues with failed payments due to this check on bibliotek.kk.dk, for reasons we are not quite sure of yet.

However, the system should err on the side of caution here, since any failure in this part of the process results in defrauding the paying customer. Basically, we take his money, but does not mark his bill as paid.

This change also obsoletes all the session juggling code in https://github.com/dingproject/ding/blob/master/ding_dibs/ding_dibs.module#L60, but we should probably wait before removing that, since it currently causes no harm.

### CODE REVIEW

**Comment by cableman** [comment]
Approved, will just wait with the merge until 1.8.0 is final.

Is there a lighthouse ticket for this fix ? It should be assigned to the 1.8.1 release.

**Comment by mikl** [comment]
Now there is: [LH#1906](https://libraryding.lighthouseapp.com/projects/27862-hovedspor/tickets/1906-fjernet-unodig-validering-pa-dibs-betalingscallback-der-i-visse-tilfaelde-resulterer-i-betalinger-der-ikke-bliver-registreret).

**Comment by kasperg** [comment]
Great!

**Comment by wiredloose** [comment]
This sounds great! In Vejle we have had exactly the problem you mention above ("we take his money, but does not mark his bill as paid."), and I have pulled a lot of hairs trying to figure it out. I even started to formulate a theory around it being an IE 7-related issue (based on our stream of errors found).

I look forward to implementing the pull request - in the hope that errors will calm down finally.

**Comment by cableman** [comment]
Reviewed and approved

**Pull request merged**
