### PR TITLE
Reduce statuses allowing reservation of periodicals

### PR DESCRIPTION
**Pull request by kasperg**
This should fix [#1824](https://libraryding.lighthouseapp.com/projects/27862-hovedspor/tickets/1824-reserverknap-ved-tidsskrifter-der-er-undervejs).

### CODE REVIEW

**Comment by cableman** [comment]
I may be missing something here, but would reducing the different statuses (removing periodical) not prevent reservation of periodicals ?

if (in_array($issue_holding['status'], $reservable_statuses)) {
  $issue['reservable'] = TRUE;
  ........
}

**Comment by kasperg** [comment]
Perhaps. The changes are made in accordance with [Steens explanation in #1824](https://libraryding.lighthouseapp.com/projects/27862-hovedspor/tickets/1824-reserverknap-ved-tidsskrifter-der-er-undervejs#ticket-1824-9).

**Comment by cableman** [comment]
This is true for aakb, but it may not be true for the other libraries. (Gitte will look into it)

**Comment by kasperg** [comment]
This required further investigation. The pull has to be put on hold until after 1.7.0.

**Comment by cableman** [comment]
It have be decided that this have to be part of 1.7.

**Pull request merged**
